#!/usr/bin/env sh
# ─────────────────────────────────────────────────────────────────────────────
# HawkGate — kernel/configure.sh
#
# Probes the build toolchain and development libraries, then writes a
# configured Makefile with the correct compiler flags for this system.
#
# Usage:
#   ./configure.sh                  # auto-detect everything
#   CLANG=clang-17 ./configure.sh   # override a specific tool
#
# Environment overrides (all optional):
#   BPF_SRC, BPF_OBJ, BPF_SKEL     BPF source / object / skeleton filenames
#   USER_SRC, USER_CLI, TARGET      userspace source filenames and binary name
#   CLANG, GCC, BPFTOOL, MAKE_BIN  toolchain overrides
#   BPF_BASE_FLAGS                  extra clang BPF flags
# ─────────────────────────────────────────────────────────────────────────────

set -eu

SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
MAKEFILE_PATH="$SCRIPT_DIR/Makefile"

# ── file name defaults ────────────────────────────────────────────────────────
BPF_SRC=${BPF_SRC:-hg_tc.bpf.c}
BPF_OBJ=${BPF_OBJ:-hg_tc.bpf.o}
BPF_SKEL=${BPF_SKEL:-hg_tc.skel.h}
USER_SRC=${USER_SRC:-hg_control.c}
USER_CLI=${USER_CLI:-hg_cli.c}
TARGET=${TARGET:-hgctl}

# ── tool defaults ─────────────────────────────────────────────────────────────
CLANG=${CLANG:-clang}
GCC=${GCC:-gcc}
BPFTOOL=${BPFTOOL:-bpftool}
MAKE_BIN=${MAKE_BIN:-make}

# ── flag defaults ─────────────────────────────────────────────────────────────
BPF_BASE_FLAGS=${BPF_BASE_FLAGS:--O2 -g -target bpf}

# ── required headers ─────────────────────────────────────────────────────────
VMLINUX_HEADER=${VMLINUX_HEADER:-vmlinux.h}

# ─────────────────────────────────────────────────────────────────────────────
info() { printf '[configure] %s\n' "$1"; }
fail() { printf '[configure] error: %s\n' "$1" >&2; exit 1; }

check_cmd() {
    if ! command -v "$1" >/dev/null 2>&1; then
        fail "required command not found: $1 — install it and re-run configure.sh"
    fi
    info "  found $1 → $(command -v "$1")"
}

check_file() {
    if [ ! -f "$SCRIPT_DIR/$1" ]; then
        fail "required source file not found: $1"
    fi
}

pkg_has() {
    command -v pkg-config >/dev/null 2>&1 && pkg-config --exists "$1" 2>/dev/null
}

# ─────────────────────────────────────────────────────────────────────────────
info "── checking build tools ──────────────────────────────────────────────"
check_cmd "$CLANG"
check_cmd "$GCC"
check_cmd "$BPFTOOL"
check_cmd "$MAKE_BIN"

info "── checking kernel version ───────────────────────────────────────────"
KVER=$(uname -r)
KMAJ=$(echo "$KVER" | cut -d. -f1)
KMIN=$(echo "$KVER" | cut -d. -f2)
if [ "$KMAJ" -lt 5 ] || { [ "$KMAJ" -eq 5 ] && [ "$KMIN" -lt 13 ]; }; then
    fail "kernel $KVER is too old — HawkGate requires Linux >= 5.13 (bpf_skb_set_tstamp)"
fi
info "  kernel $KVER — ok"

info "── checking source files ─────────────────────────────────────────────"
check_file "$BPF_SRC"
check_file "$USER_SRC"
check_file "$USER_CLI"
check_file "$VMLINUX_HEADER"
check_file "hg_tc.bpf.h"
check_file "hg_common.h"
check_file "hg_user.h"

info "── probing libbpf / libelf / zlib ───────────────────────────────────"
LIBBPF_CFLAGS=""
LIBBPF_LIBS="-lbpf -lelf -lz"

if pkg_has libbpf; then
    LIBBPF_CFLAGS=$(pkg-config --cflags libbpf)
    LIBBPF_LIBS=$(pkg-config --libs libbpf)
    info "  libbpf via pkg-config: $LIBBPF_LIBS"

    if pkg_has libelf; then
        LIBBPF_LIBS="$LIBBPF_LIBS $(pkg-config --libs libelf)"
    fi
    if pkg_has zlib; then
        LIBBPF_LIBS="$LIBBPF_LIBS $(pkg-config --libs zlib)"
    else
        LIBBPF_LIBS="$LIBBPF_LIBS -lz"
    fi
else
    info "  pkg-config entry for libbpf not found — falling back to -lbpf -lelf -lz"
fi

# compile-link smoke test
if ! printf '#include <bpf/libbpf.h>\n#include <bpf/bpf.h>\nint main(void){return 0;}\n' | \
    "$GCC" -x c - $LIBBPF_CFLAGS $LIBBPF_LIBS -o /dev/null >/dev/null 2>&1; then
    fail "libbpf headers or link flags are not usable.
       Install: apt install libbpf-dev libelf-dev zlib1g-dev   (Debian/Ubuntu)
                yum install libbpf-devel elfutils-libelf-devel  (RHEL/Fedora)"
fi
info "  libbpf compile+link smoke test — ok"

# ─────────────────────────────────────────────────────────────────────────────
info "── writing Makefile ──────────────────────────────────────────────────"
cat > "$MAKEFILE_PATH" <<MAKE
# ─────────────────────────────────────────────────────────────────────────────
# HawkGate — kernel/Makefile  (auto-generated by configure.sh)
# Regenerate with: ./configure.sh
# ─────────────────────────────────────────────────────────────────────────────

# ── file names ────────────────────────────────────────────────────────────────
BPF_SRC      ?= $BPF_SRC
BPF_OBJ      ?= $BPF_OBJ
BPF_SKEL     ?= $BPF_SKEL
USER_SRC     ?= $USER_SRC
USER_CLI     ?= $USER_CLI
TARGET       ?= $TARGET

# ── tools ─────────────────────────────────────────────────────────────────────
CLANG        ?= $CLANG
GCC          ?= $GCC
BPFTOOL      ?= $BPFTOOL

# ── flags ─────────────────────────────────────────────────────────────────────
BPF_FLAGS    ?= $BPF_BASE_FLAGS
USER_CFLAGS  ?= -O2 -g -Wall -Wextra $LIBBPF_CFLAGS
USER_LIBS    ?= $LIBBPF_LIBS

# ── phony targets ─────────────────────────────────────────────────────────────
.PHONY: all clean rebuild

all: \$(TARGET)

# ── step 1: compile BPF kernel program ───────────────────────────────────────
\$(BPF_OBJ): \$(BPF_SRC) hg_tc.bpf.h hg_common.h
	\$(CLANG) \$(BPF_FLAGS) -c \$< -o \$@

# ── step 2: generate libbpf skeleton ─────────────────────────────────────────
\$(BPF_SKEL): \$(BPF_OBJ)
	\$(BPFTOOL) gen skeleton \$< > \$@

# ── step 3: compile userspace binary ─────────────────────────────────────────
\$(TARGET): \$(USER_CLI) \$(USER_SRC) \$(BPF_SKEL) hg_user.h hg_common.h
	\$(GCC) \$(USER_CFLAGS) \$(USER_CLI) \$(USER_SRC) -o \$@ \$(USER_LIBS)

rebuild: clean all

clean:
	rm -f \$(BPF_OBJ) \$(BPF_SKEL) \$(TARGET)
MAKE

info "── configuration complete ────────────────────────────────────────────"
info ""
info "  Next steps:"
info "    1. Generate vmlinux.h for your kernel (if not already present):"
info "         bpftool btf dump file /sys/kernel/btf/vmlinux format c > vmlinux.h"
info "    2. Build:"
info "         make"
info "    3. Run (as root):"
info "         sudo ./hgctl start -i br0"
info ""
